create table public.persons (
  id bigint generated by default as identity not null,
  tree_id uuid not null,
  data jsonb not null,
  constraint persons_pkey primary key (id, tree_id),
  constraint persons_tree_id_fkey foreign KEY (tree_id) references trees (id) on delete CASCADE
) TABLESPACE pg_default;